development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: charms_development
  pool: 5
  username: root
  password: qwerty00

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: charms_testing
  pool: 5
  username: root
  password: qwerty00

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: charms_produciton
  pool: 5
  username: root
  password: 
